# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(606, 489)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 0, 341, 91))
        self.label.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/tf_logo/img/tf.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.label_2.setStyleSheet("font: 63 14pt \"URW Gothic\";")
        self.label_2.setObjectName("label_2")
        self.signIn_frame = QtWidgets.QFrame(self.centralwidget)
        self.signIn_frame.setGeometry(QtCore.QRect(130, 110, 321, 261))
        self.signIn_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.signIn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signIn_frame.setObjectName("signIn_frame")
        self.layoutWidget = QtWidgets.QWidget(self.signIn_frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 271, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("font: 25 19pt \"URW Bookman\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.username_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.password_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.widget = QtWidgets.QWidget(self.signIn_frame)
        self.widget.setGeometry(QtCore.QRect(30, 220, 281, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_button = QtWidgets.QPushButton(self.widget)
        self.register_button.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.register_button.setObjectName("register_button")
        self.horizontalLayout.addWidget(self.register_button)
        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.register_frame = QtWidgets.QFrame(self.centralwidget)
        self.register_frame.setEnabled(True)
        self.register_frame.setGeometry(QtCore.QRect(110, 100, 371, 311))
        self.register_frame.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.register_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.register_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.register_frame.setLineWidth(1)
        self.register_frame.setObjectName("register_frame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.register_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 30, 271, 225))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setStyleSheet("font: 25 19pt \"URW Bookman\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.reg_username_input = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.reg_username_input.setObjectName("reg_username_input")
        self.verticalLayout_2.addWidget(self.reg_username_input)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.reg_password_input = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.reg_password_input.setObjectName("reg_password_input")
        self.verticalLayout_2.addWidget(self.reg_password_input)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.register_key = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.register_key.setObjectName("register_key")
        self.verticalLayout_2.addWidget(self.register_key)
        self.widget1 = QtWidgets.QWidget(self.register_frame)
        self.widget1.setGeometry(QtCore.QRect(90, 260, 211, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reg_cancel_button = QtWidgets.QPushButton(self.widget1)
        self.reg_cancel_button.setMaximumSize(QtCore.QSize(100, 100))
        self.reg_cancel_button.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.reg_cancel_button.setObjectName("reg_cancel_button")
        self.horizontalLayout_2.addWidget(self.reg_cancel_button)
        self.reg_submit_button = QtWidgets.QPushButton(self.widget1)
        self.reg_submit_button.setMaximumSize(QtCore.QSize(100, 100))
        self.reg_submit_button.setStyleSheet("font: 25 14pt \"URW Bookman\";")
        self.reg_submit_button.setObjectName("reg_submit_button")
        self.horizontalLayout_2.addWidget(self.reg_submit_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Belge Kriptolama Sistemi"))
        self.label_7.setText(_translate("MainWindow", "Giriş Yapın"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_4.setText(_translate("MainWindow", "Şifre"))
        self.register_button.setText(_translate("MainWindow", "KAYIT OL"))
        self.submit_button.setText(_translate("MainWindow", "ONAYLA"))
        self.label_8.setText(_translate("MainWindow", "Kayıt Olun"))
        self.label_9.setText(_translate("MainWindow", "Email"))
        self.label_5.setText(_translate("MainWindow", "Şifre"))
        self.label_10.setText(_translate("MainWindow", "Kayıt Parolası"))
        self.reg_cancel_button.setText(_translate("MainWindow", "IPTAL"))
        self.reg_submit_button.setText(_translate("MainWindow", "Kayıt Ol"))
import logos_rc
